from setuptools import setup
from subprocess import call
import bibupdate, datetime, sys

install_requires = ['fuzzywuzzy >= 0.2']
# need to do the following properly...there's no point checking the version
# number on the system creating the distribution.
if sys.version_info[:2] < (2, 7):
    install_requires += [ 'argparse','ordereddict>=1.1' ]

# for generating ctan release log
ctan_specs=r'''# Generated: {today}
contribution=bibupdate
version={version}
name={author}
email={author_email}
summary={description}
directory=/support/bibupdate
DoNotAnnounce=0
license=free
freeversion=gpl
file=bibupdate.tar.gz
'''

# for creating the latex and pdf versions of the documentation in the doc directory
preamble=r'''\usepackage[a4paper,margin=15mm]{{geometry}}
\usepackage[colorlinks=true,linkcolor=blue,urlcolor=blue]{{hyperref}}
\hypersetup{{pdfcreator={{ Generated by python + rst2latex + pdfLaTeX }},
            pdfinfo={{Author  ={{ {author} }},
                     Keywords={{ {keywords} }},
                     License ={{ {license} }},
                     Subject ={{ {description} }},
                     Title   ={{ Bibupdate - version {version} }}
            }},
}}
'''

# generate the README file
if 'readme' in sys.argv:
    with open('README.rst','w') as rst_readme:
      rst_readme.write(bibupdate.__doc__)

    # we set --no-doc-title to stop rst2latex from overwriting the document title above
    preamble=' --no-doc-title --latex-preamble="{latex}"'.format(latex=preamble.format( **bibupdate.meta_data ))
    call('rst2latex.py {opts} README.rst README.tex'.format(opts=preamble), shell=True)
    call('pdflatex README && pdflatex README', shell=True)

elif 'ctan' in sys.argv:
    bibupdate.meta_data['today']='{:%d, %b %Y}'.format(datetime.date.today())
    with open('bibupdate.ctan','w') as ctan:
        ctan.write( ctan_specs.format(**bibupdate.meta_data) )
    print('To upload to ctan run: ctanupload -F bibupdate.ctan')
else:
    setup(name=bibupdate.meta_data.name,
          author=bibupdate.meta_data.author,
          author_email=bibupdate.author_email,
          description=bibupdate.meta_data.description,
          keywords=bibupdate.meta_data.keywords,
          license=bibupdate.meta_data.license,
          url=bibupdate.meta_data.url,
          version=bibupdate.meta_data.version,

          long_description=bibupdate.__doc__,

          py_modules = ['bibupate'],

          classifiers=[
              'Development Status :: 5 - Production/Stable',
              'Environment :: Console',
              'Intended Audience :: Science/Research',
              'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
              'Natural Language :: English',
              'Programming Language :: Python :: 2.7',
              'Topic :: Text Processing',
              'Topic :: Text Processing :: Markup :: LaTeX',
              'Topic :: Utilities'
          ],

          install_requires=install_requires,

          entry_points={'console_scripts': ['bibupdate = bibupdate:main', ],},
    )
